name: Github Post Comment

on:
  workflow_call:
    inputs:
      # Define the input parameters for the workflow
      github_repository:
        required: true
        type: string
        description: "The GitHub repository in the format 'owner/repo'"
      github_event_pull_request_number:
        required: true
        type: number
        description: "The pull request number to list modified files for"
      encoded_comment_title:
        required: false
        type: string
        description: "The base64 encoded comment title"
      encoded_comment_outputs:
        required: false
        type: string
        description: "The base64 encoded comment outputs"
      encoded_comment_results:
        required: false
        type: string
        description: "The base64 encoded comment results from previous steps."
      artifact_id:
        required: false
        type: string
        description: "The ID of the uploaded artifact"
      artifact_url:
        required: false
        type: string
        description: "The URL of the uploaded artifact"
      owner:
        required: true
        description: "Owner of the repository"
        type: string
      repositories:
        required: true
        description: "Comma-separated list of repositories to generate tokens for"
        type: string
    secrets:
      github_app_id:
        required: true
        description: "GitHub App ID for token generation"
      github_app_private_key:
        required: true
        description: "Private key for the GitHub App to generate a token"
      github_secret_token:
        required: true
        description: "The GitHub token to authenticate API requests"

jobs:
  github_post_comment:
    name: main
    runs-on: ubuntu-latest
    steps:
      # Step to generate GitHub App token
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.github_app_id }}
          private-key: ${{ secrets.github_app_private_key }}
          owner: ${{ inputs.owner }}
          repositories: "${{ inputs.repositories }},gitops-tools"

      # Step to checkout the code
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.4.2
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}

      # Step to add artifact references if provided
      - name: Add Artifact References
        id: add_artifact_references
        if: inputs.artifact_id != ''
        env:
          INPUT_GITHUB_ARTIFACT_ID: ${{ inputs.artifact_id }}
          INPUT_GITHUB_ARTIFACT_URL: ${{ inputs.artifact_url }}
        run: |
          # Add artifact references to the comment

          ARTIFACT_COMMENT="Please, download the artifact here: [${INPUT_GITHUB_ARTIFACT_ID}](${INPUT_GITHUB_ARTIFACT_URL})"
          echo "artifact_comment=${ARTIFACT_COMMENT}" >> $GITHUB_OUTPUT

      # Step to post the comment in opened Github Pull Request
      - name: Post Comment
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.github_secret_token }}
          INPUT_GITHUB_REPOSITORY: ${{ inputs.github_repository }}
          INPUT_GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ inputs.github_event_pull_request_number }}
          ENCODED_COMMENT_TITLE: ${{ inputs.encoded_comment_title }}
          ENCODED_COMMENT_OUTPUTS: ${{ inputs.encoded_comment_outputs }}
          ENCODED_COMMENT_RESULTS: ${{ inputs.encoded_comment_results }}
          ARTIFACT_COMMENT: ${{ steps.add_artifact_references.outputs.artifact_comment }}
        run: |
          # Post the output to the Pull Request comment

          WORKSPACE_DIR=$(git rev-parse --show-toplevel)
          CI_DIR="${WORKSPACE_DIR}/tools/ci"

          bash "${CI_DIR}"/github-post-comment.sh "${INPUT_GITHUB_TOKEN}" "${INPUT_GITHUB_REPOSITORY}" "${INPUT_GITHUB_EVENT_PULL_REQUEST_NUMBER}" "${ENCODED_COMMENT_TITLE}" "${ENCODED_COMMENT_OUTPUTS}" "${ENCODED_COMMENT_RESULTS}" "${ARTIFACT_COMMENT}"
