name: PR Diff Check

on:
  workflow_call:
    inputs:
      # Define the input parameters for the workflow
      github_base_ref:
        required: true
        type: string
        description: The base branch of the pull request.
      github_head_ref:
        required: true
        type: string
        description: The head branch of the pull request.
      comparison_branches:
        description: "Comma-separated list of branches to check against (e.g., dev,qa,staging)"
        required: true
        type: string
      owner:
        required: true
        description: "Owner of the repository"
        type: string
      repositories:
        required: true
        description: "Comma-separated list of repositories to generate tokens for"
        type: string
    secrets:
      github_app_id:
        required: true
        description: "GitHub App ID for token generation"
      github_app_private_key:
        required: true
        description: "Private key for the GitHub App to generate a token"
    outputs:
      # Define the output parameters for the workflow
      encoded_comment_title:
        description: "The base64 encoded comment title"
        value: ${{ jobs.diff_check.outputs.encoded_comment_title }}
      encoded_comment_outputs:
        description: "The base64 encoded comment outputs"
        value: ${{ jobs.diff_check.outputs.encoded_comment_outputs }}
      main_outcome:
        description: "The status of the check pr job"
        value: ${{ jobs.diff_check.outputs.main_outcome }}

jobs:
  diff_check:
    runs-on: ubuntu-latest

    steps:
      # Step to generate GitHub App token
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.github_app_id }}
          private-key: ${{ secrets.github_app_private_key }}
          owner: ${{ inputs.owner }}
          repositories: "${{ inputs.repositories }},gitops-tools"

      # Step to checkout the code
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.4.2
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}

      # Step to run the commit ancestry check
      - name: Run commit ancestry check
        id: main
        env:
          COMPARISON_BRANCHES: ${{ inputs.comparison_branches }}
          INPUT_GITHUB_BASE_BRANCH: ${{ inputs.github_base_ref }}
          INPUT_GITHUB_HEAD_BRANCH: ${{ inputs.github_head_ref }}
        run: |
          # Check if all commits from the PR branch are present in the specified branches

          WORKSPACE_DIR=$(git rev-parse --show-toplevel)
          CI_DIR="${WORKSPACE_DIR}/tools/ci"
          SHELL_OUTPUTS_FILE="shell_outputs.txt"

          bash "${CI_DIR}"/github-pr-diff-check.sh "${COMPARISON_BRANCHES}" "${INPUT_GITHUB_BASE_BRANCH}" "${INPUT_GITHUB_HEAD_BRANCH}" | tee $SHELL_OUTPUTS_FILE

          # capture the output of the script, filtering lines that start with #
          SHELL_OUTPUTS=$(grep '^#' $SHELL_OUTPUTS_FILE)

          # Print the captured output for debugging purposes, excluding the leading #
          echo "SHELL_OUTPUTS=${SHELL_OUTPUTS:1}"

          encoded_comment_title=$(echo "${SHELL_OUTPUTS:1}" | awk -F '|' '{print $1}')
          encoded_comment_outputs=$(echo "${SHELL_OUTPUTS:1}" | awk -F '|' '{print $2}')

          echo "encoded_comment_title=${encoded_comment_title}" >> $GITHUB_OUTPUT
          echo "encoded_comment_outputs=${encoded_comment_outputs}" >> $GITHUB_OUTPUT
    outputs:
      encoded_comment_title: ${{ steps.main.outputs.encoded_comment_title }}
      encoded_comment_outputs: ${{ steps.main.outputs.encoded_comment_outputs }}
      main_outcome: ${{ steps.main.outcome }}
