name: List PR Files

on:
  workflow_call:
    inputs:
      # Define the input parameters for the workflow
      github_repository:
        required: true
        type: string
        description: "The GitHub repository in the format 'owner/repo'"
      github_event_pull_request_number:
        required: true
        type: number
        description: "The pull request number to list modified files for"
      owner:
        required: false
        description: "Owner of the repository"
        type: string
      repositories:
        required: false
        description: "Comma-separated list of repositories to generate tokens for"
        type: string
      skip_token_generation_for_tools_repository:
        required: false
        type: boolean
        default: false
        description: "Skip GitHub App token generation for specific repositories."
    secrets:
      github_app_id:
        required: false
        description: "GitHub App ID for token generation"
      github_app_private_key:
        required: false
        description: "Private key for the GitHub App to generate a token"
      github_secret_token:
        required: true
        description: "The GitHub token to authenticate API requests"
    outputs:
      # Define the output parameters for the workflow
      pr_files_count:
        description: "The count of modified files in the pull request"
        value: ${{ jobs.github_list_pr_files.outputs.pr_files_count }}
      encoded_modified_files:
        description: "The list of modified files in the pull request, encoded in base64"
        value: ${{ jobs.github_list_pr_files.outputs.encoded_modified_files }}

jobs:
  github_list_pr_files:
    name: main
    runs-on: ubuntu-latest
    steps:
      # Step to generate GitHub App token
      - name: Generate GitHub App Token
        if: ${{ !inputs.skip_token_generation_for_tools_repository }}
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.github_app_id }}
          private-key: ${{ secrets.github_app_private_key }}
          owner: ${{ inputs.owner }}
          repositories: "${{ inputs.repositories }},gitops-tools"

      # Step to checkout the code
      - name: Checkout code
        if: ${{ !inputs.skip_token_generation_for_tools_repository }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.4.2
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}

      # Step to check out the code without token
      - name: Checkout Code
        if: ${{ inputs.skip_token_generation_for_tools_repository }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.4.2

      # Step to list modified files in the pull request
      - name: List Modified Files
        id: list_modified_files
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.github_secret_token }}
          INPUT_GITHUB_REPOSITORY: ${{ inputs.github_repository }}
          INPUT_GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ inputs.github_event_pull_request_number }}
          SKIP_TOKEN_GENERATION_FOR_TOOLS_REPOSITORY: ${{ inputs.skip_token_generation_for_tools_repository }}
        run: |
          # List modified files in the pull request using the custom script

          WORKSPACE_DIR=$(git rev-parse --show-toplevel)
          CI_DIR="${WORKSPACE_DIR}/tools/ci"
          SHELL_OUTPUTS_FILE="shell_outputs.txt"

          if [[ "$SKIP_TOKEN_GENERATION_FOR_TOOLS_REPOSITORY" == "true" ]]; then
            CI_DIR="${WORKSPACE_DIR}/ci"
          fi

          bash "${CI_DIR}"/github-list-pr-files.sh "${INPUT_GITHUB_TOKEN}" "${INPUT_GITHUB_REPOSITORY}" "${INPUT_GITHUB_EVENT_PULL_REQUEST_NUMBER}" | tee $SHELL_OUTPUTS_FILE

          # capture the output of the script, filtering lines that start with #
          SHELL_OUTPUTS=$(grep '^#' $SHELL_OUTPUTS_FILE)

          # Print the captured output for debugging purposes, excluding the leading #
          echo "SHELL_OUTPUTS=${SHELL_OUTPUTS:1}"

          pr_files_count=$(echo "${SHELL_OUTPUTS:1}" | awk -F '|' '{print $1}')
          encoded_modified_files=$(echo "${SHELL_OUTPUTS:1}" | awk -F '|' '{print $2}')

          echo "pr_files_count=${pr_files_count}" >> $GITHUB_OUTPUT
          echo "encoded_modified_files=${encoded_modified_files}" >> $GITHUB_OUTPUT
    outputs:
      encoded_modified_files: ${{ steps.list_modified_files.outputs.encoded_modified_files }}
      pr_files_count: ${{ steps.list_modified_files.outputs.pr_files_count }}
