name: Commit Validations

on:
  pull_request:
    branches:
      - main

jobs:
  commit_lint:
    name: Run Commit Lint
    uses: ./.github/workflows/commit-lint.yml
    with:
      owner: ${{ github.repository_owner }}
      repositories: ${{ github.event.repository.name }}
    secrets:
      github_app_id: ${{ secrets.CREATE_TOKEN_APP_ID }}
      github_app_private_key: ${{ secrets.CREATE_TOKEN_APP_PRIVATE_KEY }}
