name: Filter working directory

on:
  workflow_call:
    inputs:
      # Define the input parameters for the workflow
      working_directory_filter:
        required: true
        type: string
        description: "The working directory filter to apply"
      encoded_modified_files_to_filter:
        required: true
        type: string
        description: "The base64 encoded list of modified files to filter"
      owner:
        required: true
        description: "Owner of the repository"
        type: string
      repositories:
        required: true
        description: "Comma-separated list of repositories to generate tokens for"
        type: string
    secrets:
      github_app_id:
        required: true
        description: "GitHub App ID for token generation"
      github_app_private_key:
        required: true
        description: "Private key for the GitHub App to generate a token"
    outputs:
      # Define the output parameters for the workflow
      working_dirs_count:
        description: "The number of modified files in the working directory"
        value: ${{ jobs.terragrunt_filter_working_dir.outputs.working_dirs_count }}
      encoded_working_dirs:
        description: "The base64 encoded list filtered working directory"
        value: ${{ jobs.terragrunt_filter_working_dir.outputs.encoded_working_dirs }}

jobs:
  terragrunt_filter_working_dir:
    name: main
    runs-on: ubuntu-latest
    steps:
      # Step to generate GitHub App token
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.github_app_id }}
          private-key: ${{ secrets.github_app_private_key }}
          owner: ${{ inputs.owner }}
          repositories: "${{ inputs.repositories }},gitops-tools"

      # Step to checkout the code
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.4.2
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}

      - name: Filter Modified Files
        id: filter_modified_files
        env:
          FILTER: ${{ inputs.working_directory_filter }}
          ENCODED_MODIFIED_FILES_TO_FILTER: ${{ inputs.encoded_modified_files_to_filter }}
        run: |
          # Filter modified files by environment working directory

          WORKSPACE_DIR=$(git rev-parse --show-toplevel)
          CI_DIR="${WORKSPACE_DIR}/tools/ci"
          SHELL_OUTPUTS_FILE="shell_outputs.txt"

          bash "${CI_DIR}"/terragrunt-filter-working-dir.sh "${FILTER}" "${ENCODED_MODIFIED_FILES_TO_FILTER}" | tee $SHELL_OUTPUTS_FILE

          # capture the output of the script, filtering lines that start with #
          SHELL_OUTPUTS=$(grep '^#' $SHELL_OUTPUTS_FILE)

          # Print the captured output for debugging purposes, excluding the leading #
          echo "SHELL_OUTPUTS=${SHELL_OUTPUTS:1}"

          working_dirs_count=$(echo "${SHELL_OUTPUTS:1}" | awk -F '|' '{print $1}')
          encoded_working_dirs=$(echo "${SHELL_OUTPUTS:1}" | awk -F '|' '{print $2}')

          echo "working_dirs_count=${working_dirs_count}" >> $GITHUB_OUTPUT
          echo "encoded_working_dirs=${encoded_working_dirs}" >> $GITHUB_OUTPUT
    outputs:
      working_dirs_count: ${{ steps.filter_modified_files.outputs.working_dirs_count }}
      encoded_working_dirs: ${{ steps.filter_modified_files.outputs.encoded_working_dirs }}
