name: Terragrunt plan

on:
  workflow_call:
    inputs:
      # Define the input parameters for the workflow
      encoded_working_dirs:
        description: "Base64 encoded working directories"
        required: true
        type: string
      github_repository:
        description: "The GitHub repository in the format 'owner/repo'"
        required: true
        type: string
      github_run_id:
        description: "GitHub run ID"
        required: true
        type: string
      github_event_pull_request_number:
        description: "GitHub event pull request number"
        required: true
        type: number
      owner:
        required: true
        description: "Owner of the repository"
        type: string
      repositories:
        required: true
        description: "Comma-separated list of repositories to generate tokens for"
        type: string
    secrets:
      # Define the secrets required for the workflow
      github_app_id:
        required: true
        description: "GitHub App ID for token generation"
      github_app_private_key:
        required: true
        description: "Private key for the GitHub App to generate a token"
      github_secret_token:
        required: true
        description: "The GitHub token to call modules from other repositories"
      infracost_api_key:
        description: "Infracost API key"
        required: true
    outputs:
      # Define the output parameters for the workflow
      encoded_comment_title:
        description: "The base64 encoded comment title"
        value: ${{ jobs.terragrunt_plan.outputs.encoded_comment_title }}
      encoded_comment_outputs:
        description: "The base64 encoded comment outputs"
        value: ${{ jobs.terragrunt_plan.outputs.encoded_comment_outputs }}
      comment_status:
        description: "The status of the comment"
        value: ${{ jobs.terragrunt_plan.outputs.comment_status }}
      artifact_id:
        description: "The ID of the uploaded artifact"
        value: ${{ jobs.terragrunt_plan.outputs.artifact_id }}
      artifact_url:
        description: "The URL of the uploaded artifact"
        value: ${{ jobs.terragrunt_plan.outputs.artifact_url }}
      main_outcome:
        description: "The status of the Terragrunt plan job"
        value: ${{ jobs.terragrunt_plan.outputs.main_outcome }}

jobs:
  terragrunt_plan:
    name: main
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566

    steps:
      # Step to generate GitHub App token
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.github_app_id }}
          private-key: ${{ secrets.github_app_private_key }}
          owner: ${{ inputs.owner }}
          repositories: "${{ inputs.repositories }},gitops-tools"

      # Step to checkout the code
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.4.2
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}

      # Caching Terraform and Terragrunt dependencies
      - name: Cache Terragrunt
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/terragrunt/providers
          key: provider-cache-${{ runner.os }}-${{ hashFiles('**/aws.hcl') }}

      # Step to install dependencies
      - name: Install Dependencies
        run: |
          # Install necessary dependencies

          sudo apt-get update -y && \
          sudo apt-get install -y unzip direnv

      # Step to set up the repository
      - name: Setup Repository
        run: |
          # Set up the repository

          SKIP=enable_pre_commit,init_git_submodule ./bootstrap.sh # this script should be present in the caller repository

          # Extract the updated PATH and write it to GITHUB_ENV
          NEW_PATH=$(direnv exec . bash -c 'echo $PATH')
          echo "PATH=$NEW_PATH" >> $GITHUB_ENV

      # Step to run Terragrunt plan
      - name: Terragrunt Plan
        id: main
        env:
          ENCODED_WORKING_DIRS: ${{ inputs.encoded_working_dirs }}
          INPUT_GITHUB_REPOSITORY: ${{ inputs.github_repository }}
          INPUT_GITHUB_RUN_ID: ${{ inputs.github_run_id }}
          INPUT_GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ inputs.github_event_pull_request_number }}
          INPUT_GITHUB_TOKEN: ${{ secrets.github_secret_token }}
          INFRACOST_API_KEY: ${{ secrets.infracost_api_key }}
        run: |
          # Generate a Terragrunt plan

          WORKSPACE_DIR=$(git rev-parse --show-toplevel)
          CI_DIR="${WORKSPACE_DIR}/tools/ci"
          SHELL_OUTPUTS_FILE="shell_outputs.txt"

          bash "${CI_DIR}"/terragrunt-plan.sh "${ENCODED_WORKING_DIRS}" "${INPUT_GITHUB_REPOSITORY}" "${INPUT_GITHUB_RUN_ID}" "${INPUT_GITHUB_EVENT_PULL_REQUEST_NUMBER}" "${INPUT_GITHUB_TOKEN}" "${INFRACOST_API_KEY}" | tee $SHELL_OUTPUTS_FILE

          # capture the output of the script, filtering lines that start with #
          SHELL_OUTPUTS=$(grep '^#' $SHELL_OUTPUTS_FILE)

          # Print the captured output for debugging purposes, excluding the leading #
          echo "SHELL_OUTPUTS=${SHELL_OUTPUTS:1}"

          comment_status=$(echo "${SHELL_OUTPUTS:1}" | awk -F '|' '{print $1}')
          encoded_comment_title=$(echo "${SHELL_OUTPUTS:1}" | awk -F '|' '{print $2}')
          encoded_comment_outputs=$(echo "${SHELL_OUTPUTS:1}" | awk -F '|' '{print $3}')
          artifact_path_filename=$(echo "${SHELL_OUTPUTS:1}" | awk -F '|' '{print $4}')

          echo "comment_status=${comment_status}" >> $GITHUB_OUTPUT
          echo "encoded_comment_title=${encoded_comment_title}" >> $GITHUB_OUTPUT
          echo "encoded_comment_outputs=${encoded_comment_outputs}" >> $GITHUB_OUTPUT
          echo "artifact_path_filename=${artifact_path_filename}" >> $GITHUB_OUTPUT
        # to ensure comment postage even if this step fails
        continue-on-error: true

      # Step to upload comment contents if fallback is needed
      - name: Upload Comment Contents
        id: upload_comment
        if: steps.main.outputs.comment_status == 'fallback' && steps.main.outputs.artifact_path_filename != ''
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: ${{ steps.main.outputs.artifact_path_filename }}
          retention-days: 5
          overwrite: true

    outputs:
      encoded_comment_title: ${{ steps.main.outputs.encoded_comment_title }}
      encoded_comment_outputs: ${{ steps.main.outputs.encoded_comment_outputs }}
      comment_status: ${{ steps.main.outputs.comment_status }}
      artifact_id: ${{ steps.upload_comment.outputs.artifact-id }}
      artifact_url: ${{ steps.upload_comment.outputs.artifact-url }}
      main_outcome: ${{ steps.main.outcome }}
